rules:
  empty-line-between-blocks: 2
  indentation:
    - 2
    - size: 2
  no-ids: 2
  no-vendor-prefixes: 0
  space-before-brace: 2
  url-quotes: 2
  leading-zero: 0
  no-qualifying-elements: 0
  clean-import-paths:
    - 1
    - leading-underscore: true
    - filename-extension: false
