version: 2

jobs:
  build:
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Configure user.name
          command: git config --global user.name $GITHUB_USER_NAME
      - run:
          name: Configure user.name
          command: git config --global user.email $GITHUB_USER_EMAIL
      - run:
          name: Deploy
          command: $(yarn bin)/gulp deploy
      - run:
          name: Build
          command: $(yarn bin)/gulp build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
