version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: $(yarn bin)/gulp build
  deploy:
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Configure user.name
          command: git config --global user.name $GITHUB_USER_NAME
      - run:
          name: Configure user.name
          command: git config --global user.email $GITHUB_USER_EMAIL
      - run:
          name: Deploy
          command: $(yarn bin)/gulp deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
