name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency: ci-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
			- uses: actions/setup-node@v2
		    with:
				  node-version: 'lts/fermium'
